elbe-rfs CI-RT
==============

This git repository hosts all xml files for elbe based root file
systems (RFS). Those RFS are deployed on the CI-RT test targets.

For a better understanding, have a look at the detailed explanation of
the https://ci-rt.linutronix.de/RT-Test/about.jsp[CI-RT infrastructure
setup].


Download RFS
------------

The elbe based RFS are already built an can be downloaded
https://ci-rt.linutronix.de/download/target-elbe-rfs/[here].


Rebuild the RFS
---------------

The RFS were built using elbe (version 1.9.15). They can be modified
and rebuilt. Please refer to https://elbe-rfs.org/docs/[elbe
documentation] for fundamental explanation how to use elbe.

Overlay files from SCM
~~~~~~~~~~~~~~~~~~~~~~
Instead puting the customized overlay files into an archive and have no
clear version control over these files, the overlay files are checked in
and need to be added to the recipe. To make it evident, the recipe need
some preprocessing, the file is renamed to smoketest.tmpl.
Please perform the following steps before building the receipe:

$ elbe preprocess --variant=<NAME> -o <NAME>.xml smoketest.xmltmpl
$ elbe chg_archive <NAME>.xml overlay

After this preprocessing the newly prepared rfs.xml can be used as usual.